#!/usr/bin/env python3
"""Turn the FX2 firmware .ihex into a C2 EEPROM image and a C array.

The RP2350 emulates the FX2's boot EEPROM at 0xA2, so the image produced here
is bundled into the RP2350's UF2 rather than burned into a part.

Byte 0 of the image selects the boot mode (docs/bringup-plan.md, stage 5):
  0xC2  self-boot from the image           -- production
  0xC0  our VID/PID, wait for a host RAM load -- development

--mode c0 emits a header-only image so `fx2tool load` can still iterate
quickly while the FX2 already enumerates as us.
"""

import argparse
import struct
import sys

SERIAL_MARKER = b"BSLYSERIAL"

# C2 image layout, per the Cypress FX2LP TRM and libfx2's FX2Config:
#   0      0xC0 (VID/PID only) or 0xC2 (VID/PID + firmware records)
#   1..6   VID, PID, DID, little-endian
#   7      config byte
#   8..    records: >HH length, address, then `length` data bytes
#   last   0x8001 0xE600 0x00 -- releases the 8051 from reset
CFG_DISCON = 1 << 6
CFG_400KHZ = 1 << 0
REG_CPUCS = 0xE600
MAX_RECORD = 1023   # the hardware length field is 10 bits


def read_ihex(path):
    """Minimal Intel HEX reader. The FX2 has a 16-bit address space, so only
    record types 00 (data) and 01 (EOF) can legitimately appear."""
    chunks = []
    with open(path) as f:
        for lineno, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            if not line.startswith(":"):
                raise ValueError(f"{path}:{lineno}: not an Intel HEX record")
            raw = bytes.fromhex(line[1:])
            count, addr, rtype = raw[0], (raw[1] << 8) | raw[2], raw[3]
            data = raw[4:4 + count]
            if (sum(raw) & 0xFF) != 0:
                raise ValueError(f"{path}:{lineno}: bad checksum")
            if rtype == 0x00:
                chunks.append((addr, data))
            elif rtype == 0x01:
                break
            else:
                raise ValueError(f"{path}:{lineno}: unsupported record type {rtype:02x}")
    return coalesce(chunks)


def coalesce(chunks):
    """Merge adjacent records so we emit few, large load commands."""
    out = []
    for addr, data in sorted(chunks):
        if out and out[-1][0] + len(out[-1][1]) == addr:
            out[-1] = (out[-1][0], out[-1][1] + data)
        else:
            out.append((addr, bytearray(data)))
    return out


def encode_c2(records, vid, pid, did, disconnect, i2c_400khz):
    if vid in (0x0000, 0xFFFF) or pid in (0x0000, 0xFFFF):
        raise ValueError("Windows will not enumerate a device with this VID/PID")
    image = bytearray()
    image.append(0xC2 if records else 0xC0)
    image += struct.pack("<HHH", vid, pid, did)
    image.append((CFG_DISCON if disconnect else 0) |
                 (CFG_400KHZ if i2c_400khz else 0))
    for addr, data in records:
        # On-chip RAM only: 0x0000-0x3FFF (code/data) and 0xE000-0xE1FF (scratch).
        if not (0x0000 <= addr and addr + len(data) <= 0x4000 or
                0xE000 <= addr and addr + len(data) <= 0xE200):
            raise ValueError(f"record at 0x{addr:04x}+{len(data)} is outside on-chip RAM")
        while data:
            piece, data = data[:MAX_RECORD], data[MAX_RECORD:]
            image += struct.pack(">HH", len(piece), addr)
            image += piece
            addr += len(piece)
    if records:
        image += struct.pack(">HHB", 0x8001, REG_CPUCS, 0)
    return bytes(image)


def emit_header(path, image, name):
    """C array plus the offset of the serial placeholder.

    The RP2350 patches the serial in at boot so this device and the RP2350's
    own USB device report the same iSerialNumber and the host can pair them.
    An offset of -1 means the marker was not found -- the descriptor changed,
    or the string was optimised away.
    """
    offset = image.find(SERIAL_MARKER)
    with open(path, "w") as f:
        f.write("// Generated by fx2/tools/mkc2.py -- do not edit.\n")
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write(f"#define {name.upper()}_LEN {len(image)}\n")
        f.write(f"#define {name.upper()}_SERIAL_OFFSET {offset}\n")
        f.write(f"#define {name.upper()}_SERIAL_LEN 16\n\n")
        f.write(f"static const uint8_t {name}[{len(image)}] = {{\n")
        for i in range(0, len(image), 12):
            row = ", ".join(f"0x{b:02x}" for b in image[i:i + 12])
            f.write(f"    {row},\n")
        f.write("};\n")
    if offset < 0:
        print("warning: serial marker not found in image", file=sys.stderr)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("ihex")
    p.add_argument("output")
    p.add_argument("--vid", type=lambda s: int(s, 0), required=True)
    p.add_argument("--pid", type=lambda s: int(s, 0), required=True)
    p.add_argument("--did", type=lambda s: int(s, 0), default=0x0001)
    p.add_argument("--mode", choices=("c2", "c0"), default="c2")
    p.add_argument("--header")
    p.add_argument("--name", default="fx2_boot_image")
    # 24LC-style EEPROMs at 0xA2 are 16-bit addressed; the RP2350 emulation is
    # bounded by how much of its flash we are willing to spend.
    p.add_argument("--max-size", type=lambda s: int(s, 0), default=16384)
    args = p.parse_args()

    records = read_ihex(args.ihex) if args.mode == "c2" else []
    image = encode_c2(records, args.vid, args.pid, args.did,
                      disconnect=True,     # firmware calls usb_init(disconnect=true)
                      i2c_400khz=True)
    if len(image) > args.max_size:
        raise SystemExit(f"image is {len(image)} bytes, over the {args.max_size} limit")

    with open(args.output, "wb") as f:
        f.write(image)
    if args.header:
        emit_header(args.header, image, args.name)

    print(f"{args.output}: {len(image)} bytes, mode {args.mode}, "
          f"{args.vid:04x}:{args.pid:04x}")


if __name__ == "__main__":
    main()
