// FX2 boot EEPROM emulation. The RP2350 answers as a 16-bit-addressed EEPROM
// at 0xA2 (7-bit 0x51) on i2c0, GP4/GP5, and serves the C2 image generated by
// fx2/tools/mkc2.py. There is no EEPROM on the board.
#pragma once
#include <stdbool.h>
#include <stdint.h>

typedef enum {
    FX2_BOOT_ROM,   // silent on I2C: FX2 enumerates as 04B4:8613, host RAM-loads
    FX2_BOOT_C0,    // header only: FX2 enumerates as 35F0:DB13, host RAM-loads
    FX2_BOOT_C2,    // full image: FX2 boots our firmware on its own
} fx2_boot_mode_t;

// Copy the image to RAM and patch `serial` (16 characters, the RP2350's flash
// unique ID) into the FX2's iSerialNumber, so the host can pair the two devices.
void fx2_boot_init(const char *serial);

// Takes effect at the next FX_RESET# release: the boot ROM reads the EEPROM
// only then.
void fx2_boot_set_mode(fx2_boot_mode_t mode);
fx2_boot_mode_t fx2_boot_get_mode(void);
const char *fx2_boot_mode_name(fx2_boot_mode_t mode);

uint32_t fx2_boot_image_len(void);

// Bytes read by the FX2 since the last reset release, for bring-up.
uint32_t fx2_boot_bytes_served(void);
void fx2_boot_reset_stats(void);
